// Fonts — install precompiled .cpfont families from a catalog into
// /.fonts/<Familia>/, preview each one, and pick the active family.
//
// The catalog is generated by the cp-fonts repo (CrossGlyph builds of curated
// WP-Fonts families, one .cpfont per point size, 6-18). Binaries live as
// rolling-release assets — /api/fetch does not follow redirects, so release
// URLs are resolved via relay HEAD hops before streaming straight to SD
// (same pattern as the dictionaries plugin). Previews are page renders from
// the reader's own renderer, hosted on raw.githubusercontent (no redirects,
// CORS-friendly). The active family lives in /.crosspoint/settings.json under
// "sdFontFamilyName".
CrossPoint.registerPlugin(async (container, api) => {
  // Point this at your cp-fonts fork (owner/repo).
  const CATALOG_URL = 'https://raw.githubusercontent.com/josmerod/cp-fonts/main/catalog/fonts.json';
  const CATALOG_CACHE = '/.crosspoint/fonts-catalog.json';
  const FONTS_DIR = '/.fonts';
  const SETTINGS_PATH = '/.crosspoint/settings.json';

  let catalog = null;       // parsed catalog/fonts.json
  let installed = new Map(); // family name -> Set(sizes) present on the reader
  let maxFamilies = 0;
  let filter = '';

  container.innerHTML =
    '<h2>Fonts</h2>' +
    '<p id="fx-status">Loading font catalog…</p>' +
    '<h3 style="margin:0.5em 0 0.2em">Active font</h3>' +
    '<div class="setting-row">' +
    '<span class="setting-control"><select id="fx-active" style="width:100%"></select></span>' +
    '<button type="button" class="btn-small btn-add" id="fx-set-active">Set active</button></div>' +
    '<p style="color:#666">You can also switch families on the device under Settings &gt; Font — that applies immediately; writing the file here applies after a restart.</p>' +
    '<h3 style="margin:0.8em 0 0.2em">Available families</h3>' +
    '<div class="setting-row"><span class="setting-control">' +
    '<input type="text" id="fx-search" placeholder="Filter, e.g. charter or ofl" style="width:100%"></span></div>' +
    '<div id="fx-list"></div>' +
    '<p style="color:#666">Families install to <code>/.fonts/&lt;Familia&gt;/</code> and appear in the reader\'s Settings &gt; Font picker without a reboot. ' +
    'Sizes are per-file bitmaps: leave the ones you use checked — each is a few hundred KB. ' +
    'The reader holds at most 128 installed families.</p>';

  const status = (t) => { document.getElementById('fx-status').textContent = t; };
  const listEl = document.getElementById('fx-list');
  const activeSel = document.getElementById('fx-active');

  function escapeHtml(s) {
    return String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  }

  // UTF-8-safe base64 for writeFile.
  function b64(str) {
    const bytes = new TextEncoder().encode(str);
    let bin = '';
    for (const b of bytes) bin += String.fromCharCode(b);
    return btoa(bin);
  }

  // --- catalog + installed state -------------------------------------------
  async function loadCatalog() {
    // The browser usually reaches GitHub directly (raw.githubusercontent.com
    // sends CORS headers). If it can't, let the device download the catalog to
    // SD and read it back through the same-origin /download endpoint.
    try {
      const r = await fetch(CATALOG_URL, { cache: 'no-store' });
      if (r.ok) return await r.json();
    } catch (e) {}
    const res = await api.fetchToSd(CATALOG_URL, CATALOG_CACHE, {});
    if (res.error || (res.status && (res.status < 200 || res.status >= 300))) {
      throw new Error('catalog download failed (' + (res.status || res.error) + ')');
    }
    const r = await fetch('/download?path=' + encodeURIComponent(CATALOG_CACHE));
    if (!r.ok) throw new Error('catalog readback failed');
    return JSON.parse(await r.text());
  }

  async function loadInstalled() {
    try {
      const r = await fetch('/api/fonts');
      if (!r.ok) return;
      const data = await r.json();
      maxFamilies = data.maxFamilies || 0;
      installed = new Map((data.families || []).map((f) => [f.name, new Set(f.sizes || [])]));
    } catch (e) { /* reader not reachable — treat as none installed */ }
  }

  async function readSettings() {
    const r = await fetch('/download?path=' + encodeURIComponent(SETTINGS_PATH));
    if (r.status === 404) return {};
    if (!r.ok) throw new Error('cannot read settings (' + r.status + ')');
    const text = await r.text();
    return text.trim() ? JSON.parse(text) : {};
  }

  // --- install / remove ----------------------------------------------------
  // GitHub release-asset URLs answer with a redirect, and the device's
  // /api/fetch does not follow redirects — resolve the hops here via the
  // relay (HEAD keeps the 32 KB relay cap irrelevant), then stream the final
  // URL straight to SD.
  async function resolveUrl(url) {
    for (let hop = 0; hop < 5; hop++) {
      let r;
      try { r = await api.relay('HEAD', url, {}, ''); } catch (e) { return url; }
      const s = r.status | 0;
      if (s < 300 || s >= 400) return url;
      let loc = '';
      for (const h of r.headers || []) if (String(h[0]).toLowerCase() === 'location') loc = h[1];
      if (!loc) return url;
      url = new URL(loc, url).toString();
    }
    return url;
  }

  async function installSizes(fam, pts, onProgress) {
    const files = (fam.files || []).filter((f) => pts.includes(f.pt));
    if (!files.length) throw new Error('no sizes selected');
    const dir = FONTS_DIR + '/' + fam.name;
    // /api/fonts/delete only removes a whole family, so a failed first
    // install rolls back with one delete; a failed top-up of an existing
    // family leaves its new sizes in place (they are additive — the reader
    // lists whatever sizes it finds) rather than losing the old install.
    const wasInstalled = installed.has(fam.name) && installed.get(fam.name).size > 0;
    let written = 0;
    try {
      for (let i = 0; i < files.length; i++) {
        if (onProgress) onProgress(i, files.length);
        const url = await resolveUrl(catalog.baseUrl + files[i].name);
        const dest = dir + '/' + files[i].name;
        const res = await api.fetchToSd(url, dest, {});
        if (res.error || (res.status && (res.status < 200 || res.status >= 300))) {
          throw new Error('download failed for ' + files[i].name + ' (' + (res.status || res.error) + ')');
        }
        written++;
      }
    } catch (e) {
      if (!wasInstalled && written > 0) {
        try { await removeFamily(fam.name); } catch (e2) {}
      }
      throw e;
    }
    if (onProgress) onProgress(files.length, files.length);
  }

  async function removeFamily(name) {
    const r = await fetch('/api/fonts/delete', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ family: name }),
    });
    if (!r.ok) throw new Error('delete failed (' + r.status + ')');
  }

  // --- active font ---------------------------------------------------------
  function renderActive(current) {
    const names = Array.from(installed.keys()).sort();
    activeSel.innerHTML = '<option value="">None</option>' +
      names.map((n) => '<option value="' + escapeHtml(n) + '"' + (n === current ? ' selected' : '') + '>' +
        escapeHtml(n) + '</option>').join('');
    activeSel.value = current && installed.has(current) ? current : '';
  }

  document.getElementById('fx-set-active').onclick = async () => {
    const name = activeSel.value;
    try {
      // Read-modify-write so every other setting survives. The firmware may
      // write the old value back if settings change on the device before a
      // restart; the on-device Settings > Font picker is the live path.
      const settings = await readSettings();
      if (name) settings.sdFontFamilyName = name;
      else delete settings.sdFontFamilyName;
      const res = await api.writeFile(SETTINGS_PATH, b64(JSON.stringify(settings)));
      if (res && res.ok === false) throw new Error('write failed');
      status(name
        ? 'Active font set to "' + name + '". Restart the reader (or switch on the device) to apply.'
        : 'Active font cleared. Restart the reader to apply.');
    } catch (e) {
      status('Error saving active font: ' + e.message);
    }
  };

  // --- family list ---------------------------------------------------------
  function matches(fam) {
    if (!filter) return true;
    const hay = (fam.name + ' ' + fam.title + ' ' + (fam.license || '')).toLowerCase();
    return filter.toLowerCase().split(/\s+/).every((w) => hay.includes(w));
  }

  function installedLabel(fam) {
    const have = installed.get(fam.name);
    if (!have || !have.size) return '';
    const of = fam.sizes ? have.size + '/' + fam.sizes.length : String(have.size);
    return ' <span style="color:#27ae60">Installed ' + of + (fam.sizes && have.size >= fam.sizes.length ? '' : ' sizes') + '</span>';
  }

  function renderList() {
    const families = (catalog && catalog.families) || [];
    const visible = families.filter(matches);
    listEl.innerHTML = visible.map((fam) => {
      const have = installed.get(fam.name);
      const sizes = fam.sizes || [];
      const previews = (fam.previews || []).map((p) =>
        '<img src="' + escapeHtml((catalog.rawBase || '') + p.path) + '" alt="' + escapeHtml(fam.name + ' ' + p.pt + 'pt') + '" ' +
        'style="max-width:100%;border:1px solid #ddd;border-radius:4px;margin:4px 0">').join('');
      return '<div class="setting-row">' +
        '<span class="setting-name"><strong>' + escapeHtml(fam.title || fam.name) + '</strong>' +
        installedLabel(fam) +
        '<br><span style="color:#666">' + escapeHtml(fam.description || '') + '</span>' +
        '<br><span style="color:#666">' + escapeHtml((fam.styles || []).join(' ')) + ' · ' + escapeHtml(fam.license || '') + '</span></span>' +
        '<span class="setting-control">' +
        '<button type="button" class="btn-small btn-add" id="fx-install-' + escapeHtml(fam.name) + '">' +
        (have && have.size ? 'Reinstall' : 'Install') + '</button>' +
        (have && have.size ? ' <button type="button" class="btn-small" id="fx-remove-' + escapeHtml(fam.name) + '">Remove</button>' : '') +
        '</span></div>' +
        (previews || '') +
        '<div style="margin:2px 0 10px">' + sizes.map((pt) =>
          '<label style="margin-right:8px;white-space:nowrap"><input type="checkbox" id="fx-size-' + escapeHtml(fam.name) + '-' + pt + '" checked> ' + pt + '</label>').join('') + '</div>';
    }).join('') || '<p style="color:#888">No font families match.</p>';

    for (const fam of visible) {
      const btn = document.getElementById('fx-install-' + fam.name);
      btn.onclick = async () => {
        btn.disabled = true;
        status('Installing ' + fam.title + '…');
        try {
          const pts = (fam.sizes || []).filter((pt) => {
            const cb = document.getElementById('fx-size-' + fam.name + '-' + pt);
            return !cb || cb.checked;
          });
          await installSizes(fam, pts, (done, total) => { btn.textContent = done + '/' + total; });
          await loadInstalled();
          status('Installed ' + fam.title + ' → ' + FONTS_DIR + '/' + fam.name + '/. Pick it under Settings > Font on the reader.');
          renderActive(activeSel.value);
          renderList();
        } catch (e) {
          status('Error installing ' + fam.title + ': ' + e.message);
          btn.textContent = installed.get(fam.name) && installed.get(fam.name).size ? 'Reinstall' : 'Install';
          btn.disabled = false;
        }
      };
      if (installed.get(fam.name) && installed.get(fam.name).size) {
        document.getElementById('fx-remove-' + fam.name).onclick = async function () {
          this.disabled = true;
          status('Removing ' + fam.title + '…');
          try {
            await removeFamily(fam.name);
            await loadInstalled();
            status('Removed ' + fam.title + '.');
            renderActive(activeSel.value);
            renderList();
          } catch (e) {
            status('Error removing ' + fam.title + ': ' + e.message);
            this.disabled = false;
          }
        };
      }
    }
  }

  document.getElementById('fx-search').oninput = function () {
    filter = this.value.trim();
    renderList();
  };

  // --- boot ----------------------------------------------------------------
  try {
    await loadInstalled();
    let current = '';
    try { current = (await readSettings()).sdFontFamilyName || ''; } catch (e) {}
    renderActive(current);
    catalog = await loadCatalog();
    const n = (catalog.families || []).length;
    status(n + ' families available.' +
      (maxFamilies && installed.size >= maxFamilies ? ' Family limit reached (' + maxFamilies + ') — remove one first.' : ''));
    renderList();
  } catch (e) {
    status('Error: ' + e.message);
  }
});
