// Fonts — install precompiled .cpfont families from a catalog into
// /.fonts/<Familia>/, preview each one, and pick the active family.
//
// The catalog is generated by the cp-fonts repo (CrossGlyph builds of curated
// WP-Fonts families, one .cpfont per point size, 6-18). Binaries live as
// rolling-release assets — /api/fetch does not follow redirects, so release
// URLs are resolved via relay HEAD hops before streaming straight to SD
// (same pattern as the dictionaries plugin). Previews are page renders from
// the reader's own renderer, hosted on raw.githubusercontent (no redirects,
// CORS-friendly). The active family lives in /.crosspoint/settings.json under
// "sdFontFamilyName".
CrossPoint.registerPlugin(async (container, api) => {
  // Point this at your cp-fonts fork (owner/repo).
  const CATALOG_URL = 'https://raw.githubusercontent.com/josmerod/cp-fonts/main/catalog/fonts.json';
  const CATALOG_CACHE = '/.crosspoint/fonts-catalog.json';
  const FONTS_DIR = '/.fonts';
  const SETTINGS_PATH = '/.crosspoint/settings.json';

  let catalog = null;       // parsed catalog/fonts.json
  let installed = new Map(); // family name -> Set(sizes) present on the reader
  let maxFamilies = 0;
  let filter = '';
  let licenseFilter = '';

  container.innerHTML =
    '<h2>Fonts</h2>' +
    '<p id="fx-status">Loading font catalog…</p>' +
    '<h3 style="margin:0.5em 0 0.2em">Active font</h3>' +
    '<div class="setting-row">' +
    '<span class="setting-control"><select id="fx-active" style="width:100%"></select></span>' +
    '<button type="button" class="btn-small btn-add" id="fx-set-active">Set active</button></div>' +
    '<p style="color:#666">You can also switch families on the device under Settings &gt; Font — that applies immediately; writing the file here applies after a restart.</p>' +
    '<h3 style="margin:0.8em 0 0.2em">Available families</h3>' +
    '<div class="setting-row"><span class="setting-control">' +
    '<input type="text" id="fx-search" placeholder="Filter, e.g. charter or ofl" style="width:60%"></span>' +
    '<span class="setting-control"><select id="fx-license" style="width:38%"></select></span></div>' +
    '<div id="fx-list"></div>' +
    '<p style="color:#666">Families install to <code>/.fonts/&lt;Familia&gt;/</code> and appear in the reader\'s Settings &gt; Font picker without a reboot. ' +
    'Sizes are per-file bitmaps: leave the ones you use checked — each is a few hundred KB. ' +
    'The reader holds at most 128 installed families.</p>';

  const status = (t) => { document.getElementById('fx-status').textContent = t; };
  const listEl = document.getElementById('fx-list');
  const activeSel = document.getElementById('fx-active');

  function escapeHtml(s) {
    return String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  }

  // UTF-8-safe base64 for writeFile.
  function b64(str) {
    const bytes = new TextEncoder().encode(str);
    let bin = '';
    for (const b of bytes) bin += String.fromCharCode(b);
    return btoa(bin);
  }

  async function post(path, params) {
    return fetch(path, {
      method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams(params).toString(),
    });
  }

  // Some firmware builds' /api/fetch fails with "cannot create file" when the
  // destination folder is missing (the recursive-parents fix is newer than the
  // X4 Pro release firmware). /mkdir exists on every build, so create both
  // levels here — tolerantly: "already exists" (400) and even a transient
  // failure are ignored; a genuinely missing folder will still surface through
  // the fetch error that follows.
  async function ensureFamilyDir(name) {
    try { await post('/mkdir', { name: '.fonts', path: '/' }); } catch (e) {}
    try { await post('/mkdir', { name: name, path: FONTS_DIR }); } catch (e) {}
  }

  // --- catalog + installed state -------------------------------------------
  async function loadCatalog() {
    // The browser usually reaches GitHub directly (raw.githubusercontent.com
    // sends CORS headers). If it can't, let the device download the catalog to
    // SD and read it back through the same-origin /download endpoint.
    try {
      const r = await fetch(CATALOG_URL, { cache: 'no-store' });
      if (r.ok) return await r.json();
    } catch (e) {}
    const res = await api.fetchToSd(CATALOG_URL, CATALOG_CACHE, {});
    if (res.error || (res.status && (res.status < 200 || res.status >= 300))) {
      throw new Error('catalog download failed (' + (res.status || res.error) + ')');
    }
    const r = await fetch('/download?path=' + encodeURIComponent(CATALOG_CACHE));
    if (!r.ok) throw new Error('catalog readback failed');
    return JSON.parse(await r.text());
  }

  async function loadInstalled() {
    try {
      const r = await fetch('/api/fonts');
      if (!r.ok) return;
      const data = await r.json();
      maxFamilies = data.maxFamilies || 0;
      installed = new Map((data.families || []).map((f) => [f.name, new Set(f.sizes || [])]));
    } catch (e) { /* reader not reachable — treat as none installed */ }
  }

  async function readSettings() {
    const r = await fetch('/download?path=' + encodeURIComponent(SETTINGS_PATH));
    if (r.status === 404) return {};
    if (!r.ok) throw new Error('cannot read settings (' + r.status + ')');
    const text = await r.text();
    return text.trim() ? JSON.parse(text) : {};
  }

  // --- install / remove ----------------------------------------------------
  // GitHub release-asset URLs answer with a redirect, and the device's
  // /api/fetch does not follow redirects — resolve the hops here via the
  // relay (HEAD keeps the 32 KB relay cap irrelevant), then stream the final
  // URL straight to SD.
  async function resolveUrl(url) {
    for (let hop = 0; hop < 5; hop++) {
      let r;
      try { r = await api.relay('HEAD', url, {}, ''); } catch (e) { return url; }
      const s = r.status | 0;
      if (s < 300 || s >= 400) return url;
      let loc = '';
      for (const h of r.headers || []) if (String(h[0]).toLowerCase() === 'location') loc = h[1];
      if (!loc) return url;
      url = new URL(loc, url).toString();
    }
    return url;
  }

  async function installSizes(fam, pts, onProgress) {
    const files = (fam.files || []).filter((f) => pts.includes(f.pt));
    if (!files.length) throw new Error('no sizes selected');
    const dir = FONTS_DIR + '/' + fam.name;
    // /api/fonts/delete only removes a whole family, so a failed first
    // install rolls back with one delete; a failed top-up of an existing
    // family leaves its new sizes in place (they are additive — the reader
    // lists whatever sizes it finds) rather than losing the old install.
    const wasInstalled = installed.has(fam.name) && installed.get(fam.name).size > 0;
    await ensureFamilyDir(fam.name);
    let done = 0;
    try {
      for (const f of files) {
        if (onProgress) onProgress(done, files, fam);
        const destFile = dir + '/' + f.name;
        let res = await api.fetchToSd(catalog.baseUrl + f.name, destFile, {});
        if (res.error || (res.status && (res.status < 200 || res.status >= 300))) {
          // A catalog backed by redirecting URLs (e.g. GitHub releases):
          // /api/fetch does not follow redirects, so resolve the hops via the
          // relay and retry once. Each extra hop costs the reader a full TLS
          // handshake, which is why the catalog's baseUrl points at a host
          // that answers 200 directly.
          const url = await resolveUrl(catalog.baseUrl + f.name);
          res = await api.fetchToSd(url, destFile, {});
        }
        if (res.error || (res.status && (res.status < 200 || res.status >= 300))) {
          throw new Error('download failed for ' + f.name + ' (' + (res.status || res.error) + ')');
        }
        done++;
      }
    } catch (e) {
      if (!wasInstalled && done > 0) {
        try { await removeFamily(fam.name); } catch (e2) {}
      }
      throw e;
    }
    if (onProgress) onProgress(done, files, fam);
    return files;
  }

  // /api/fetch writes do not mark the font registry dirty on this firmware,
  // so a family installed through it stays invisible to /api/fonts and to
  // Settings > Font until a reboot. Re-uploading one already-installed file
  // through /api/fonts/upload (the /fonts page path) marks the registry and
  // triggers the rescan — the family shows up live, no reboot.
  async function refreshRegistry(fam, installedFiles) {
    const files = (installedFiles || []).slice().sort((a, b) => a.size - b.size);
    if (!files.length) return false;
    try {
      const r = await fetch('/download?path=' + encodeURIComponent(FONTS_DIR + '/' + fam.name + '/' + files[0].name));
      if (!r.ok) throw new Error('readback failed');
      const fd = new FormData();
      fd.append('family', fam.name);
      fd.append('file', new Blob([await r.arrayBuffer()]), files[0].name);
      const up = await fetch('/api/fonts/upload', { method: 'POST', body: fd });
      if (!up.ok) throw new Error('upload failed (' + up.status + ')');
      return true;
    } catch (e) {
      return false; // files are on the card; the reader just needs a restart
    }
  }

  async function removeFamily(name) {
    const r = await fetch('/api/fonts/delete', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ family: name }),
    });
    if (!r.ok) throw new Error('delete failed (' + r.status + ')');
  }

  // --- active font ---------------------------------------------------------
  function renderActive(current) {
    const names = Array.from(installed.keys()).sort();
    activeSel.innerHTML = '<option value="">None</option>' +
      names.map((n) => '<option value="' + escapeHtml(n) + '"' + (n === current ? ' selected' : '') + '>' +
        escapeHtml(n) + '</option>').join('');
    activeSel.value = current && installed.has(current) ? current : '';
  }

  document.getElementById('fx-set-active').onclick = async () => {
    const name = activeSel.value;
    try {
      // Read-modify-write so every other setting survives. The firmware may
      // write the old value back if settings change on the device before a
      // restart; the on-device Settings > Font picker is the live path.
      const settings = await readSettings();
      if (name) settings.sdFontFamilyName = name;
      else delete settings.sdFontFamilyName;
      const res = await api.writeFile(SETTINGS_PATH, b64(JSON.stringify(settings)));
      if (res && res.ok === false) throw new Error('write failed');
      status(name
        ? 'Active font set to "' + name + '". Restart the reader (or switch on the device) to apply.'
        : 'Active font cleared. Restart the reader to apply.');
    } catch (e) {
      status('Error saving active font: ' + e.message);
    }
  };

  // --- family list ---------------------------------------------------------
  const GROUP_ORDER = ['Serif', 'Slab', 'Sans', 'Mono', 'Display', 'Other'];

  function matches(fam) {
    if (licenseFilter && (fam.license || '') !== licenseFilter) return false;
    if (!filter) return true;
    const hay = (fam.name + ' ' + fam.title + ' ' + (fam.license || '')).toLowerCase();
    return filter.toLowerCase().split(/\s+/).every((w) => hay.includes(w));
  }

  function licenseHtml(fam) {
    const lic = fam.license || '';
    return fam.licenseUrl
      ? '<a href="' + escapeHtml(fam.licenseUrl) + '" target="_blank" title="license text" style="color:inherit">' + escapeHtml(lic) + '</a>'
      : escapeHtml(lic);
  }

  function installedLabel(fam) {
    const have = installed.get(fam.name);
    if (!have || !have.size) return '';
    const of = fam.sizes ? have.size + '/' + fam.sizes.length : String(have.size);
    return ' <span style="color:#27ae60">Installed ' + of + (fam.sizes && have.size >= fam.sizes.length ? '' : ' sizes') + '</span>';
  }

  const mb = (n) => (n / 1048576).toFixed(1) + ' MB';

  function previewsHtml(fam) {
    return (fam.previews || []).map((p) =>
      '<a href="' + escapeHtml((catalog.rawBase || '') + p.path) + '" target="_blank" title="' + p.pt + 'pt — open full size">' +
      '<img src="' + escapeHtml((catalog.rawBase || '') + p.path) + '" alt="' + escapeHtml(fam.name + ' ' + p.pt + 'pt') + '" ' +
      'style="max-width:26%;min-width:110px;border:1px solid #ddd;border-radius:4px;margin:4px 6px 4px 0"></a>').join('');
  }

  function renderList() {
    const families = (catalog && catalog.families) || [];
    const visible = families.filter(matches);
    // Collapsible category groups keep a large catalog navigable; an active
    // filter re-opens the groups that still hold matches.
    const groups = new Map();
    for (const fam of visible) {
      const g = fam.group || 'Other';
      if (!groups.has(g)) groups.set(g, []);
      groups.get(g).push(fam);
    }
    const order = [...groups.keys()].sort((a, b) => {
      const key = (x) => { const i = GROUP_ORDER.indexOf(x); return i < 0 ? GROUP_ORDER.length : i; };
      return key(a) - key(b);
    });
    const filtering = !!(filter || licenseFilter);

    const row = (fam) => {
      const have = installed.get(fam.name);
      const sizes = fam.sizes || [];
      const total = (fam.files || []).reduce((n, f) => n + f.size, 0);
      return '<div class="setting-row">' +
        '<span class="setting-name"><strong>' + escapeHtml(fam.title || fam.name) + '</strong>' +
        installedLabel(fam) +
        '<br><span style="color:#666">' + escapeHtml(fam.description || '') + '</span>' +
        '<br><span style="color:#666">' + escapeHtml((fam.styles || []).join(' ')) + ' · ' + licenseHtml(fam) +
        ' · ' + sizes.length + ' sizes · ' + mb(total) + '</span></span>' +
        '<span class="setting-control">' +
        '<button type="button" class="btn-small" id="fx-preview-' + escapeHtml(fam.name) + '">Preview</button> ' +
        '<button type="button" class="btn-small btn-add" id="fx-install-' + escapeHtml(fam.name) + '">' +
        (have && have.size ? 'Reinstall' : 'Install') + '</button>' +
        (have && have.size ? ' <button type="button" class="btn-small" id="fx-remove-' + escapeHtml(fam.name) + '">Remove</button>' : '') +
        '</span></div>' +
        '<div style="margin:2px 0 4px;font-size:0.92em">' + sizes.map((pt) =>
          '<label style="margin-right:8px;white-space:nowrap"><input type="checkbox" id="fx-size-' + escapeHtml(fam.name) + '-' + pt + '" checked> ' + pt + '</label>').join('') +
        ' <a href="#" id="fx-all-' + escapeHtml(fam.name) + '">all</a> / <a href="#" id="fx-none-' + escapeHtml(fam.name) + '">none</a></div>' +
        '<div id="fx-previews-' + escapeHtml(fam.name) + '"></div>';
    };

    listEl.innerHTML = order.map((g) =>
      '<details style="margin:6px 0"' + (filtering ? ' open' : '') + '>' +
      '<summary style="cursor:pointer;padding:4px 0"><strong>' + escapeHtml(g) + '</strong> · ' + groups.get(g).length + '</summary>' +
      groups.get(g).map(row).join('') + '</details>').join('') ||
      '<p style="color:#888">No font families match.</p>';

    for (const fam of visible) {
      const sizes = fam.sizes || [];
      const setAll = (v) => {
        for (const pt of sizes) {
          const cb = document.getElementById('fx-size-' + fam.name + '-' + pt);
          if (cb) cb.checked = v;
        }
      };
      document.getElementById('fx-all-' + fam.name).onclick = (e) => { if (e) e.preventDefault(); setAll(true); };
      document.getElementById('fx-none-' + fam.name).onclick = (e) => { if (e) e.preventDefault(); setAll(false); };

      // Previews load on demand — a catalog with many families must not pull
      // every preview image on page open.
      const pvBtn = document.getElementById('fx-preview-' + fam.name);
      pvBtn.onclick = () => {
        const box = document.getElementById('fx-previews-' + fam.name);
        if (box.innerHTML) { box.innerHTML = ''; pvBtn.textContent = 'Preview'; }
        else { box.innerHTML = previewsHtml(fam); pvBtn.textContent = 'Hide'; }
      };

      const btn = document.getElementById('fx-install-' + fam.name);
      btn.onclick = async () => {
        btn.disabled = true;
        status('Installing ' + fam.title + '…');
        try {
          const pts = sizes.filter((pt) => {
            const cb = document.getElementById('fx-size-' + fam.name + '-' + pt);
            return !cb || cb.checked;
          });
          const t0 = Date.now();
          const installedFiles = await installSizes(fam, pts, (done, files, f) => {
            const doneBytes = files.reduce((n, x, i) => n + (i < done ? x.size : 0), 0);
            const totalBytes = files.reduce((n, x) => n + x.size, 0);
            btn.textContent = done + '/' + files.length;
            status('Installing ' + f.title + '… ' + done + '/' + files.length + ' · ' + mb(doneBytes) + ' of ' + mb(totalBytes));
          });
          const refreshed = await refreshRegistry(fam, installedFiles);
          await loadInstalled();
          const n = pts.length;
          status('Installed ' + fam.title + ' (' + n + ' sizes) → ' + FONTS_DIR + '/' + fam.name + '/ in ' +
            Math.round((Date.now() - t0) / 1000) + 's. ' +
            (refreshed
              ? 'Pick it under Settings > Font on the reader.'
              : 'Restart the reader to see it under Settings > Font.'));
          renderActive(activeSel.value);
          renderList();
        } catch (e) {
          status('Error installing ' + fam.title + ': ' + e.message);
          btn.textContent = installed.get(fam.name) && installed.get(fam.name).size ? 'Reinstall' : 'Install';
          btn.disabled = false;
        }
      };
      if (installed.get(fam.name) && installed.get(fam.name).size) {
        document.getElementById('fx-remove-' + fam.name).onclick = async function () {
          this.disabled = true;
          status('Removing ' + fam.title + '…');
          try {
            await removeFamily(fam.name);
            await loadInstalled();
            status('Removed ' + fam.title + '.');
            renderActive(activeSel.value);
            renderList();
          } catch (e) {
            status('Error removing ' + fam.title + ': ' + e.message);
            this.disabled = false;
          }
        };
      }
    }
  }

  document.getElementById('fx-search').oninput = function () {
    filter = this.value.trim();
    renderList();
  };

  const licenseSel = document.getElementById('fx-license');
  licenseSel.onchange = function () {
    licenseFilter = this.value;
    renderList();
  };

  function renderLicenseFilter() {
    const families = (catalog && catalog.families) || [];
    const licenses = [...new Set(families.map((f) => f.license || '').filter(Boolean))].sort();
    licenseSel.innerHTML = '<option value="">All licenses</option>' +
      licenses.map((l) => '<option value="' + escapeHtml(l) + '"' + (l === licenseFilter ? ' selected' : '') + '>' +
        escapeHtml(l) + '</option>').join('');
  }

  // --- boot ----------------------------------------------------------------
  try {
    await loadInstalled();
    let current = '';
    try { current = (await readSettings()).sdFontFamilyName || ''; } catch (e) {}
    renderActive(current);
    catalog = await loadCatalog();
    renderLicenseFilter();
    const n = (catalog.families || []).length;
    status(n + ' families available.' +
      (maxFamilies && installed.size >= maxFamilies ? ' Family limit reached (' + maxFamilies + ') — remove one first.' : ''));
    renderList();
  } catch (e) {
    status('Error: ' + e.message);
  }
});
